# This is a basic workflow to help you get started with Actions

name: Build and Push Image to Docker Hub

on:
  workflow_run:
    workflows: ["Clean And Build Project"]   # Tên chính xác của workflow A
    types:
      - completed
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  japan-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Chỉ chạy nếu success
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0 # Thay đổi version phù hợp với project của bạn

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    # Bước build Image và Push lên Docker Hub
    # Chỉ nên chạy bước này nếu các bước trên thành công
    - name: Login to Docker Hub
      if: github.event_pull_request.merged == true # Tùy chọn: chỉ push khi PR được merge
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAM }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      if: github.event_pull_request.merged == true
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USER_NAM }}/my-sample-dotnet-8-api:latest
