# This is a basic workflow to help you get started with Actions

name: Push notify to Slack Dev4

on:
  workflow_run:
    workflows: ["Build and Push Image to Docker Hub"]   # TÃªn chÃ­nh xÃ¡c cá»§a workflow A
    types:
      - completed
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  brazil-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  # Chá»‰ cháº¡y náº¿u success
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Notify Slack on Success
        uses: slackapi/slack-github-action@v1.26.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "ðŸš€ Deploy thÃ nh cÃ´ng! Image má»›i Ä‘Ã£ push lÃªn Docker Hub",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*ðŸš€ Deploy thÃ nh cÃ´ng!*\nImage má»›i Ä‘Ã£ push lÃªn Docker Hub\nâ€¢ Repo: ${{ github.repository }}\nâ€¢ Branch: ${{ github.ref_name }}\nâ€¢ <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|Xem workflow>"
                  }
                }
              ]
            }
