name: SCHEDULED-WORFLOW

on:
  schedule:
    # Chạy mỗi 2 phút
    - cron: '0 0 * * *' 
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  hello:
    runs-on: ubuntu-slim
    
    steps:
      - name: Echo Hello Python
        run: echo "hello python, good work"
        
      - name: Print current time
        run: echo "Job ran at $(date)"