name: WORKFLOW-NET-01

on:
  push:
    branches:
      - &branch_name "feat/add-new-string"
    tags:
      - &tagLabled test-notify
  pull_request:
    branches:
      - *branch_name
    types:
      - labeled

jobs:
  log-simple-only:
    if: github.ref_name == 'feat/add-new-string' && (github.event.label.name == vars.TAGS_TEST_NOTIFY)
    runs-on:
      - ubuntu-slim
    steps:
      - name: "console simple log"
        run: |
          echo 'Hello world'
          echo 'Current label in vars is "${{vars.TAGS_TEST_NOTIFY}}"'

  always-log:
    runs-on: ubuntu-slim
    steps:
      - name: "always console log"
        run: |
          echo "Always. Hi! there"
          echo "2 + 3 = $((2 + 3))"          

  get-info:
    runs-on:
      - ubuntu-slim
    steps:
      - name: "log information"
        run: |
          echo "LABEL NAME => ${{ github.event.label.name }} , ref_name = ${{ github.ref_name}}"